# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J3vOtbYuhL-M4B1awIJW6kBkTZM2Vc1t
"""

# @title Importando bibliotecas

import streamlit as st
import numpy as np
import os
import pydicom
import gdown
import zipfile
import zipfile
import shutil
from tensorflow.keras.models import load_model
from PIL import Image

# @title Parâmetros

# Listar arquivos .dcm
dicom_files = []

# Resultados armazenados em lista
resultados = []

# Ajuste para o modelo
IMG_SIZE = 128
MODEL_ID = "1zfggM4S9HxRphPcGN2dCrWWswYr2kEMV"  # ID do Google Drive
MODEL_PATH = "classifier.h5"
MODEL_URL = f"https://drive.google.com/uc?id={MODEL_ID}"

# Layout das colunas
NUM_COLS = 3

# @title Funções

# Função para obter os arquivos DICOM que estão no arquivo zipado enviado pelo usuário
def funcObterArquivoDicom(dicom_dir):
  for root, dirs, files in os.walk(dicom_dir):
      for file in files:
          if file.endswith(".dcm"):
              dicom_files.append(os.path.join(root, file))

  return dicom_files

# Função para ordenar as fatias do arquivo DICOM
def funcOrdenarFatias(dicom_files):
  # Ordenar por InstanceNumber (ordem axial)
  slices = [pydicom.dcmread(f) for f in dicom_files]
  slices = [s for s in slices if hasattr(s, 'InstanceNumber')]
  slices.sort(key=lambda s: s.InstanceNumber)

  # Converter para volume 3D
  volume = np.stack([s.pixel_array for s in slices])

  # st.write("Volume 3D:", volume.shape)  # (profundidade, altura, largura)

  return slices, volume

# @title Layout

# # Titulo da página
st.set_page_config(page_title='Trabalho de Graduação', page_icon='🥼', layout='wide')
st.title('Classificação de Anomalias em TC de Tórax')
st.info('Identificação e localização de anomalias causadas por câncer de pulmão, em tomografias de tórax, utilizando inteligência artifical | Trabalho de Graduação referente ao curso de Engenharia Biomédica da Universidade Federal do ABC')
#
# Menu Lateral
st.sidebar.header("Menu")
st.sidebar.caption("Leitura de arquivos DICOM.")
#
# # Upload do arquivo
uploaded_zip = st.file_uploader(label='Upload your DICOM file:', type="zip")

# @title Processamento dos arquivos DICOM


# Baixa o modelo se não existir
if not os.path.exists(MODEL_PATH):
    with st.spinner("Baixando o modelo..."):
        gdown.download(MODEL_URL, MODEL_PATH, quiet=False)

# Carrega o modelo treinado
modelo = load_model('classifier.h5')

if uploaded_zip:
    temp_dir = "temp_upload"

    # Limpar e criar diretório temporário
    if os.path.exists(temp_dir):
        shutil.rmtree(temp_dir)
    os.makedirs(temp_dir)

    # Salvar arquivo zip
    zip_path = os.path.join(temp_dir, "uploaded.zip")
    with open(zip_path, "wb") as f:
        f.write(uploaded_zip.getbuffer())

    # Extrair arquivos do zip
    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(temp_dir)

    # Filtros
    if 'filtro' not in st.session_state:
        st.session_state.filtro = "Todos"

    # Chamando a função para obter os arquivos DICOM do arquivo zipado
    dicom_files = funcObterArquivoDicom(temp_dir)

    # Ler e ordenar as fatias
    slices, volume = funcOrdenarFatias(dicom_files)

    # Passo 2: botões para filtrar
    if 'filtro' not in st.session_state:
        st.session_state.filtro = "Todos"

    col1, col2 = st.columns(2)

    with col1:
      flex_filtro = st.container(border=True, gap="small", height=175)

      flex_filtro.subheader("Filtro")

      flex_botoes = flex_filtro.container(horizontal=True, horizontal_alignment="left")

      if flex_botoes.button("Todos", key="btn_todos"):
          st.session_state.filtro = "Todos"
      elif flex_botoes.button("Apenas Câncer", key="btn_cancer"):
          st.session_state.filtro = "Apenas Câncer"
      elif flex_botoes.button("Apenas Saudável", key="btn_saudavel"):
          st.session_state.filtro = "Apenas Saudável"

      flex_filtro.write(f"Filtro ativo: {st.session_state.filtro}")


    # Processando os dados
    for dicom_path in dicom_files:
        ds = pydicom.dcmread(dicom_path)
        img = ds.pixel_array.astype(np.float32)

        img_pil = Image.fromarray(img)
        img_resized = img_pil.resize((IMG_SIZE, IMG_SIZE))
        img_to_show = img_resized.convert("L")

        img_array = np.array(img_resized)
        img_array = np.expand_dims(img_array, axis=-1)
        img_array = np.expand_dims(img_array, axis=0)
        img_array = img_array / 255.0

        pred = modelo.predict(img_array)
        pred_prob = float(pred[0][0])
        pred_class = "Câncer" if pred_prob > 0.5 else "Saudável"

        resultados.append({
            "img": img_to_show,
            "pred_class": pred_class,
            "pred_prob": pred_prob,
            "filename": os.path.basename(dicom_path)
        })

    num_cancer = [r for r in resultados if r['pred_class'] == 'Câncer']
    num_saudavel = [r for r in resultados if r['pred_class'] == 'Saudável']

    with col2:
      flex_dados = st.container(border=True, gap="small", height=175)
        
      flex_dados.write("Dados")
      flex_dados.write(f"Arquivos DICOM encontrados: {len(dicom_files)}")
      flex_dados.write(f"Slices detectados com câncer: {len(num_cancer)}")
      flex_dados.write(f"Slices detectados como saudável: {len(num_saudavel)}")

    # Exibir imagens filtradas lado a lado

    filtrado = []
    if st.session_state.filtro == "Todos":
        filtrado = resultados
    elif st.session_state.filtro == "Apenas Câncer":
        filtrado = num_cancer
    else:
        filtrado = num_saudavel

    for i in range(0, len(filtrado), NUM_COLS):
        cols = st.columns(min(NUM_COLS, len(filtrado) - i))
        batch = filtrado[i:i+NUM_COLS]

        for j, item in enumerate(batch):
            with cols[j]:
                st.image(item["img"], caption=f"{item['filename']}")
                st.write(f"Predição: {item['pred_class']} ({item['pred_prob']:.3f})")
