[theme]
base = "dark"
primaryColor = "#9c27b0"              # Roxo vibrante (botões, highlights)
backgroundColor = "#121212"           # Fundo preto escuro
secondaryBackgroundColor = "#2a1a47"  # Roxo escuro quase preto para divider/painéis
textColor = "#ffffff"                 # Texto branco puro
font = "sans serif"
