[theme]
base = "dark"
primaryColor = "#9c27b0"              # Roxo vibrante para destaques
backgroundColor = "#121212"           # Fundo escuro principal
secondaryBackgroundColor = "#1a1a1a"  # Quase preto, neutro para divisores/painéis
textColor = "#e1bee7"                 # Texto lilás claro
font = "sans serif"
